from .usuario import Usuario
from .parcela import Parcela
from .cultivo import Cultivo
from .actividad_agricola import ActividadAgricola
from .observacion import Observacion
from .fotografia import Fotografia
from .inspeccion import Inspeccion
from .incidencia import Incidencia
from .recomendacion import Recomendacion
from .producto_inventario import ProductoInventario
from .movimiento_inventario import MovimientoInventario
from .gasto import Gasto
from .ingreso import Ingreso
from .alerta import Alerta
from .diagnostico_ia import DiagnosticoIA
from .prediccion_cosecha import PrediccionCosecha
from .sincronizacion import Sincronizacion
